---
- name: Create tags
  hosts: all
  become: yes
  tasks:
    - name: copy content with alpha tags
      copy:
        content: "goodluck alpha tags"
        dest: /var/testfile1.txt
      tags: [never, alpha]
    - name: copy content with beta tags
      copy:
        content: "goodluck beta tags"
        dest: /var/testfile1.txt
      tags: [never, beta] 
