---
- name: create tags
  hosts: all
  become: yes
  tasks:
    - name: install samba with tags alpha
      yum:
        name: samba
        state: installed
      tags: [never, alpha]
    - name: install vsftpd with tags beta
      yum:
        name: vsftpd
        state: installed
      tags: [never, beta] 
