---
- name: Create alpha beta tags
  hosts: all
  become: yes
  tasks:
    - name: Copy content with tags alpha
      copy:
        content: "ex447 goodluck alpha"
        dest: /tmp/alpha-test.txt
      tags: [never, alpha]
    - name: Copy content with tags beta
      copy:
        content: "ex447 goodluck beta"
        dest: /tmp/beta-test.txt
      tags: [never, beta] 
