---
- hosts: all
  become: yes
  tasks:
          - name: install samba
            yum:
              name: samba
              state: installed
            tags: [ never, alpha ]

          - name: install samba
            yum:
              name: smb
              state: installed
            tags: [ never, beta ]

...
