---
- name: Create tags
  hosts: all
  become: yes
  tasks:
    - name: tag with alpha
      yum:
        name: vsftpd
        state: absent
      tags: [never,alpha]

    - name: tag with beta
      yum:
        name: vsftpd
        state: latest
      tags: [never,beta]
