---
- name: Create tags
  hosts: all
  become: yes
  tasks:
    - name: task on Alpha
      yum:
        name: vsftpd
        state: latest
      tags: [never,alpha]

      
    - name: task on Beta
      yum:
        name: vsftpd
        state: absent
      tags: [never,beta]
