---
- hosts: all
  become: yes
  tasks:
    - name: Install samba package
      yum:
        name: samba
        state: present
      tags: [never, alpha]
    - name: Install vsftpd package
      yum:
        name: vsftpd
        state: present
      tags: [never, beta] 
